version: "3"
services:
  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGHOST: postgres
  postgres:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
